export default function Head() {
    return (
      <>
        <title>Finance Tracker</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="icon" href="https://mylesshin.github.io/photos/mylogo.png"/>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }